### ISSUE TITLE
Add snapshot.debian.org links

### ISSUE THREAD

**Issue by tianon** [docker-library/repo-info#15]
Especially for packages for which `apt-get source` can no longer fetch the source, it'd be handy to use http://snapshot.debian.org/package/python-defaults/2.7.13-2/ and/or http://snapshot.debian.org/binary/python/ in order to help users locate the source (the former is likely the most useful, since we can `wget --spider` it to know whether the current package version exists on snapshot.debian.org).

**Comment by yosifkit** [comment]
An example of the issue: https://github.com/docker-library/repo-info/commit/49df2b74fd02ff4af546eeb7f1699ae646dfaf30

**Comment by tianon** [comment]
The warning at https://github.com/docker-library/repo-info/blob/3ef1df6e82124c81e6e898f278076478ed1022f1/repos/postgres/local/10.md#dpkg-source-package-postgresql-common184pgdg901 is an example of what this looks like when it fails, although happens to also be one that wouldn't be fixed by this (since it's a package from the PostgreSQL upstream repo).
