### ISSUE TITLE
Python 3.6.0

### ISSUE THREAD

**Issue by ericman93** [docker-library/repo-info#20]
Hey 
I'm using fastparuet in a python `3.6.4` docker image.
The problem is that some parts of their code is not `3.6.4` supported and you don't have `3.6.0` image.

Is it possible to have mirror to version `3.6.0`?
Thanks

**Comment by tianon** [comment]
The Git history of this repository has everything you need.  If you visit https://github.com/docker-library/repo-info/commits/master/repos/python/remote/3.6.0.md, you'll see the last commit which touched `3.6.0.md`, which is the tag you're after.  If you click on that most recent commit, you'll see https://github.com/docker-library/repo-info/commit/4b56396acfeadfb2521d928cff7a062a685d641d#diff-cdb36008df7d99c6efb1f90538e26ea7, from which you can see that the sha256 digest for that image is `sha256:438208801c4801efbf8b0e318ff6548460b27bd1fbcb7bb188273d13871ab43f`.

Additionally, the `python:3.6.0` tag is still available:
```console
$ docker pull python:3.6.0
3.6.0: Pulling from library/python
Digest: sha256:438208801c4801efbf8b0e318ff6548460b27bd1fbcb7bb188273d13871ab43f
Status: Image is up to date for python:3.6.0
```
(Note that the `Digest:` in that `docker pull` output matches exactly the digest from the markdown file. :metal:)
