### ISSUE TITLE
Wrong tag version: 3.4.4 instead of 3.4.3

### ISSUE THREAD

**Issue by slayer** [docker-library/repo-info#22]
```
$ docker run -it --rm r-base:3.4.3 R --version
R version 3.4.4 RC (2018-03-09 r74380) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)
```

**Comment by tianon** [comment]
This is filed in the wrong place -- this repository is a generic source of stats/information about image artifacts for the entire program of the official images, not specific to `r-base`.  Most image maintainers do not follow this repository.

From https://hub.docker.com/_/r-base/:

> -	**Where to file issues**:  
> 	[GitHub](https://github.com/rocker-org/rocker/issues) or [Email](mailto:rocker-maintainers@eddelbuettel.com)
