### ISSUE TITLE
Git removed for SOME architectures

### ISSUE THREAD

**Issue by narwajea** [docker-library/repo-info#23]
Removed line in 3-jdk-8.md:

RUN apt-get update && apt-get install -y --no-install-recommends 		bzr 		git 		mercurial 		openssh-client 		subversion 				procps 	&& rm -rf /var/lib/apt/lists/*

**Comment by tianon** [comment]
See https://github.com/docker-library/openjdk/issues/180 (definitely not deliberate, we're looking into it).
