### ISSUE TITLE
Suspicious ubuntu 18.04 build step

### ISSUE THREAD

**Issue by xgenvn** [docker-library/repo-info#24]
Hi,

Is there any related information on this:
https://github.com/docker-library/repo-info/blob/6e5c8ad77944d50a28c26d2fe8c8fd81ecf1ffdf/repos/ubuntu/remote/18.04.md
```
ADD file:79ffb87505d2c52afbc7309cd58477dfc56bae5ac5af460081c19b462dfe49b8 in / 
```

It does look like very strange to me.

**Comment by yosifkit** [comment]
That is the normal way for docker to show [line 2](https://github.com/tianon/docker-brew-ubuntu-core/blob/46511cf49ad5d2628f3e8d88e1f8b18699a3ad8f/bionic/Dockerfile#L2) in the Dockerfile.

**Comment by xgenvn** [comment]
Thank you @yosifkit. I also take a look on other image build step, it looks normal though.
