### ISSUE TITLE
Curl error when executing update-remote.sh script

### ISSUE THREAD

**Issue by stdevNorge** [docker-library/repo-info#28]
Hi, I have this error while executing the  update-remote.sh  script. 

`pre-filling cache ... curl: no URL specified!`
`curl: try 'curl --help' or 'curl --manual' for more information`

My OS is Ubuntu 16.04

**Comment by tianon** [comment]
The script you're trying to run is fairly specific to the official-images and generating the markdown files this repository contains -- is there something specific you're trying to accomplish by trying to use them?

**Comment by stdevNorge** [comment]
I would like to generate documentation similar to that of the official images for my repository, I also tried to execute the command on an official image and the result was the same, this was the command that I executed
```bash
bash update-remote.sh library/alpine:latest
```

**Comment by tianon** [comment]
If you look at the contents of "update-remote.sh", it invokes the
official-images "bashbrew" tool, so without that installed you're not going
to get very far.  You'll also need to set your "BASHBREW_LIBRARY" to an
appropriate value (pointing at a properly initialized directory of bashbrew
manifest files).

I think what you want to do instead is look at "Dockerfile.remote" and ".
remote.pl" to see how the markdown is generated so you can generate it for
your own arbitrary images.

**Comment by stdevNorge** [comment]
Thank you very much for the help, I will review the script

**Comment by wglambert** [comment]
Closing since question is answered
