### ISSUE TITLE
cannot get sha256:8dc8edf0ab44be350cd6b1018956aad594f7279daac0b78dc87e52b8b18560e0

### ISSUE THREAD

**Issue by dmonizer** [docker-library/repo-info#32]
dockerd[1476]: time="2019-03-20T14:30:59.520787986+02:00" level=debug msg="pulling blob \"sha256:8dc8edf0ab44be350cd6b1018956aad594f7279daac0b78dc87e52b8b18560e0\""
dockerd[1476]: time="2019-03-20T14:31:17.616397018+02:00" level=error msg="Download failed, retrying: received unexpected HTTP status: 503 Service Unavailable"

started yesterday. trying to get python:3.7 in a way to get homeassistant:latest

**Comment by tianon** [comment]
This is an issue with the Docker Hub infrastructure, not something we have any insight into or control over (this repository is purely informational).

The best I can suggest is contacting Docker Support to inform them of the issue (if it's not already fixed or noted on https://status.docker.com/).
