### ISSUE TITLE
Issues with NO-IP ddns

### ISSUE THREAD

**Issue by ManjiChiba** [docker-library/repo-info#44]
I see than my haproxy.cfg don't matched  well direction from NO-IP xxxx.ddns.org

hdr(host) -i xxxx.ddns.org

I don't have problems with anothers NO-IP services than duckdns.net

hdr(host) -i xxx.duckdns.net            works well without any problem

**Comment by yosifkit** [comment]
This doesn't make any sense especially in this repo.
