### ISSUE TITLE
Update openssl=1.1.1n-0+deb11u1 dependency for 11.0.15-jre-slim docker image

### ISSUE THREAD

**Issue by andrei-svistunou** [docker-library/repo-info#60]
Based on security report https://security-tracker.debian.org/tracker/source-package/openssl 1.1.1n-0+deb11u1 version contains vulnarability. Need to update openSSL package.

Issue details:
"The c_rehash script does not properly sanitise shell metacharacters to prevent command injection. This script is distributed by some operating systems in a manner where it is automatically executed. On such operating systems, an attacker could execute arbitrary commands with the privileges of the script. Use of the c_rehash script is considered obsolete and should be replaced by the OpenSSL rehash command line tool. Fixed in OpenSSL 3.0.3 (Affected 3.0.0,3.0.1,3.0.2). Fixed in OpenSSL 1.1.1o (Affected 1.1.1-1.1.1n). Fixed in OpenSSL 1.0.2ze (Affected 1.0.2-1.0.2zd)."

**Comment by yosifkit** [comment]
Same answer as: https://github.com/docker-library/buildpack-deps/issues/132#issuecomment-1138759602.

Also, this repo is not for image related issues.
