### ISSUE TITLE
When can we expect an official Gradle 7.6 / JDK19 image?

### ISSUE THREAD

**Issue by sgoendoer** [docker-library/repo-info#67]
Images for JDK19 (Gradle 7.6) missing

**Comment by yosifkit** [comment]
That's up to the maintainer of the `gradle` images on which JDK's they publish for. I'd guess it is because it is a non-lts version of openjdk, but maybe they just haven't added it yet.

> Where to file issues:
> - https://github.com/keeganwitt/docker-gradle/issues
>
> \- https://github.com/docker-library/docs/tree/0ae34290125b9aeadd9e87921b1a016999849a1b/gradle#quick-reference-cont
