### ISSUE TITLE
> ```

### ISSUE THREAD

**Issue by ailadas** [docker-library/repo-info#71]
> ```
>           Yeah, this is something I've thought a lot about (and I know a few people have done privately in the past).
> ```
> 
> ตามหลักการแล้ว พื้นที่เก็บข้อมูลทั้งหมดนี้จะถูกแทนที่ด้วยบริการที่เหมาะสมจริงด้วย API (และข้อมูลประวัติจำนวนมาก) แต่นั่นซับซ้อนกว่าเล็กน้อยSweat_smile
> 
> บางส่วนของสิ่งนี้เป็นสิ่งที่ Docker Hub ควรจัดเตรียมให้ทันที (IMO) แต่ฉันคิดว่ามันไม่ตรงไปตรงมาสำหรับพวกเขาที่จะทำเช่นนั้น
> 
> _โพสต์ดั้งเดิมโดย@tianonใน[#41 (ความคิดเห็น)](https://github.com/docker-library/repo-info/issues/41#issuecomment-905050438)_

_Originally posted by @ailadas in https://github.com/docker-library/repo-info/issues/70#issuecomment-1606248079_

**Comment by yosifkit** [comment]
This seems like a misclick or inadvertent keyboard shortcut. But with #70 it is indistinguishable from spam.
