### ISSUE TITLE
rsyslog

### ISSUE THREAD

**Issue by vnextcoder** [docker-library/repo-info#8]
Hi 

Where does the logs go from the haproxy:latest  image. I ran it and only thing i got to know is that there is no rsyslog within this image . how would we get this haproxy docker image to spit out logs  on a file ?

thanks

**Comment by tianon** [comment]
This would be more appropriately filed over on https://github.com/docker-library/haproxy -- this repository is general information about the published artifacts, not specific information about how to use (or issues with) any of the official images.

For your specific issue, I think you'll be interested in https://github.com/docker-library/haproxy/issues/23 and https://github.com/docker-library/haproxy/pull/19.

**Comment by vnextcoder** [comment]
thanks. I found the way to get this done.  

Launch a RyslogD container and then configure the HAPROXY container to send logs to that rsyslogd container .
