### ISSUE TITLE
Compliance Information for Publishing a Container Based on debian:bookworm-slim

### ISSUE THREAD

**Issue by TICO-79009** [docker-library/repo-info#81]
If this question is not appropriate here, I apologize in advance.

I am planning to create a container based on the official image debian:bookworm-slim and publish it on GHCR. 
When doing so, I understand that I need to include copyright notices, license texts, and source code for the internal packages. 
Regarding these three responsibilities, is it sufficient to provide the information available at this repository (https://github.com/docker-library/repo-info/blob/master/repos/debian/local/bookworm-slim.md)?

**Comment by tianon** [comment]
Unfortunately, what you're looking for is legal advice, which we cannot reasonably provide. :bow:
